spring:
  application:
    name: gateway-service

server:
  port: 4444

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


management:
  tracing:
    sampling:
      probability: 1.0